import Image from "next/image";
import { cn } from "@/lib/utils";

interface OptimizedImageProps {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  fill?: boolean;
  className?: string;
  priority?: boolean;
  sizes?: string;
  quality?: number;
}

/**
 * OptimizedImage Component
 * 
 * A wrapper around Next.js Image component with built-in optimizations:
 * - WebP format with JPEG fallback
 * - Responsive sizing
 * - Lazy loading (except priority images)
 * - Proper aspect ratios
 */
export function OptimizedImage({
  src,
  alt,
  width,
  height,
  fill,
  className,
  priority = false,
  sizes = "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
  quality = 80,
}: OptimizedImageProps) {
  // Ensure src starts with /
  const imageSrc = src.startsWith("/") ? src : `/${src}`;

  return (
    <Image
      src={imageSrc}
      alt={alt}
      width={fill ? undefined : width}
      height={fill ? undefined : height}
      fill={fill}
      className={cn("object-cover", className)}
      priority={priority}
      sizes={sizes}
      quality={quality}
      // Enable WebP format
      format="webp"
    />
  );
}

/**
 * ResponsiveImage Component
 * 
 * Provides multiple image sizes for responsive loading
 * Uses the optimized images generated by the build script
 */
interface ResponsiveImageProps {
  basename: string;
  alt: string;
  className?: string;
  priority?: boolean;
  sizes?: string;
}

export function ResponsiveImage({
  basename,
  alt,
  className,
  priority = false,
  sizes = "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
}: ResponsiveImageProps) {
  // Generate srcSet for responsive images
  const srcSet = [
    { url: `/images/optimized/${basename}-thumb.webp`, width: 400 },
    { url: `/images/optimized/${basename}-medium.webp`, width: 768 },
    { url: `/images/optimized/${basename}-optimized.jpg`, width: 1280 },
  ]
    .map((img) => `${img.url} ${img.width}w`)
    .join(", ");

  return (
    <Image
      src={`/images/optimized/${basename}-optimized.jpg`}
      alt={alt}
      fill
      className={cn("object-cover", className)}
      priority={priority}
      sizes={sizes}
      quality={80}
    />
  );
}
